sudo: required
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - DB=postgres
    - PSQL_PORT=5000
    - PSQL_HOST=localhost
    - CC_TEST_REPORTER_ID=74cbdb599d4cabc78a5dd07f26f1ddcc36910ffca3104c35c2ba66603818031c 
  matrix:
    - DJANGO=1.11.21
services:
  - docker
cache:
  pip: true
  yarn: true
  directories:
    - eventol/front/node_modules
before_install:
  - make travis-before
install:
  - make backend-install-dev
  - make travis-install-dependencies
script:
  - make travis-script
after_success:
  - make travis-after
