sudo: required
language: python
python:
  - "3.6"
env:
  global:
    - DB=postgres
    - PSQL_PORT=5000
    - PSQL_USER=eventol
    - PSQL_DBNAME=eventol
    - PSQL_HOST=localhost
    - PSQL_PASSWORD=secret
  matrix:
    - DJANGO=1.11.20
services:
  - docker
cache: pip
before_install:
  - docker run --name eventol-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=eventol -e POSTGRES_DB=eventol -p 5000:5432 -d postgres:9.6
install:
  - pip install -U pip wheel
  - pip install coverage coveralls
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - cd eventol
  - python manage.py makemigrations manager
  - python manage.py migrate
  - coverage run --source='.' pytest --cov-report term-missing --cov-report html --cov
after_success:
  - coverage report
  - coveralls
