version: '3.4'

services:
  daphne:
    restart: always
    build:
      context: ../../.
    depends_on:
      - worker
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_CONFIGURATION=Prod
    command: bash -c 'cd eventol; daphne -b 0.0.0.0 -p 8000 eventol.asgi:channel_layer'
  
  worker:
    restart: always
    build:
      context: ../../.
    env_file:
      - .env
    volumes:
      - type: bind
        source: /srv/deploys/eventoldata/static
        target: /usr/src/app/eventol/static
      - type: bind
        source: /srv/deploys/eventoldata/media
        target: /usr/src/app/eventol/media
    environment:
      - DJANGO_CONFIGURATION=Prod
    command: ./wait-for-it.sh -p 5432 -h postgres -t 40 -- ./start_eventol.sh

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - daphne
      - worker
    volumes:
      - type: bind
        source: /srv/deploys/eventoldata/static
        target: /usr/src/app/eventol/static
        read_only: true
      - type: bind
        source: /srv/deploys/eventoldata/media
        target: /usr/src/app/eventol/media
        read_only: true
    environment:
      - VIRTUAL_HOST=${HOST}
  
  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_DB=${PSQL_DBNAME}
    volumes:
      - type: bind
        source: /srv/deploys/eventoldata/postgres
        target: /var/lib/postgresql/data
  
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    depends_on:
      - nginx
    ports:
      - '${EXTERNAL_PORT}:80'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
      - type: bind
        source: ./nginx_proxy_settings.conf
        target: /etc/nginx/conf.d/eventol_settings.conf
        read_only: true
  
  redis:
    image: redis:4.0.2
    restart: always
