---
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: kibana
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: true
